# Generated by Django 4.2.30 on 2026-04-30 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lon', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='inspections/raw/')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lon', models.FloatField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='models.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fault_type', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('bounding_box', models.JSONField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved')], default='Open', max_length=50)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='models.image')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='models.panel')),
            ],
        ),
    ]
