# Generated by Django 4.2.30 on 2026-07-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_notification_remove_image_image_gps_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='priority',
            field=models.CharField(choices=[('Routine', 'Routine'), ('Urgent', 'Urgent'), ('Emergency', 'Emergency')], default='Routine', max_length=50),
        ),
        migrations.AddField(
            model_name='inspection',
            name='scan_type',
            field=models.CharField(choices=[('Thermal AI', 'Thermal AI'), ('RGB Visual', 'RGB Visual'), ('Both', 'Both')], default='Thermal AI', max_length=50),
        ),
        migrations.AddField(
            model_name='inspection',
            name='site_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
